# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/crystallang/crystal/
image: "crystallang/crystal:latest"

# Cache shards in between builds
cache:
  paths:
    - lib
    - bin

before_script:
  - crystal -v # Print out Crystal version for debugging

spec:
  script:
    - shards
    - crystal spec --error-on-warnings

format:
  script:
    - shards
    - crystal tool format --check

style:
  script:
    - shards
    - bin/ameba

nightly:
  image: "crystallang/crystal:nightly"
  allow_failure: true
  script:
    - shards --ignore-crystal-version
    - crystal spec --error-on-warnings
    - crystal tool format --check

pages:
  stage: deploy
  dependencies:
    - spec
  script:
    - crystal docs
    - mv docs/ public/
  artifacts:
    paths:
      - public
  only:
    - master
